[".oh-my-zsh/"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
refreshPeriod = "168h"

[".local/share/gnome-shell/extensions/"]
type = "archive"
url = "https://github.com/0ry0n/Resource_Monitor/releases/latest/download/Resource_Monitor@Ory0n.zip"
exact = true
refreshPeriod = "168h"
